name: Java CI with Maven

on:
  push:
    branches: ["**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validation with Maven
      run:  mvn validate -f pom.xml 
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run:  mvn compile -f pom.xml 
      
          
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Running Tests with Maven
      run:  mvn test -f pom.xml 
      
                
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Packaging with Maven
      run:  mvn package -f pom.xml && ls -la target
      
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
 
      - name: Deploy
        run: sed -i 's/personal-access-token/${{ secrets.GH_PACKAGE_REPO_PASSWORD }}/g' settings.xml && sed -i 's/username/denaumenko/g' settings.xml && mvn -B -Pgithub deploy
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
